# Generated by Django 5.1.3 on 2024-11-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0002_section_num_class_in_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=15),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('9:00 - 9:50', '9:00 - 9:50'), ('9:50 - 10:40', '9:50 - 10:40'), ('11:00 - 11:50', '11:00 - 11:50'), ('11:50 - 12:40', '11:50 - 12:40'), ('14:00 - 14:50', '14:00 - 14:50'), ('14:50 - 15:40', '14:50 - 15:40'), ('15:40 - 16:30', '15:40 - 16:30'), ('16:30 - 17:20', '16:30 - 17:20')], default='11:30 - 12:30', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='r_number',
            field=models.CharField(max_length=66, unique=True),
        ),
    ]
