# Generated by Django 5.1.3 on 2024-11-24 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0003_course_has_lab_alter_meetingtime_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='has_lab',
        ),
        migrations.AddField(
            model_name='course',
            name='number_of_classes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='course',
            name='number_of_lectures',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='course',
            name='number_of_tutorials',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
