# Generated by Django 5.1.3 on 2024-11-24 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0005_remove_course_number_of_classes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='num_class_in_week',
        ),
    ]
