# Generated by Django 5.1.4 on 2024-12-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0006_remove_section_num_class_in_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='associated_courses',
            field=models.ManyToManyField(blank=True, to='SchedulerApp.course'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
    ]
